name: "CI: Create product release"
run-name: "CI: Create product release for ${{ github.event.inputs.app }}"
on:
  workflow_dispatch:
    inputs:
      app:
        description: "app to release"
        default: 'products/hvac-runtime'
        required: true
jobs:
  demo_job_summary:
    runs-on: ubuntu-latest
    steps:
      - name: "NPM init"
        run: npm init -y

      - name: "NPM install"
        run: npm install @actions/core @actions/github

      - name: Checkout
        uses: actions/checkout@v4

      - name: Fake release version creating
        id: version
        run: |
          echo "Generating release version..."
          echo "RELEASE_VERSION=1.0.0" >> $GITHUB_ENV


      - name: Set workflow run name
        uses: .github/actions/set-run-name@v1
        with:
          run-name: "Release ${{ github.event.inputs.app }} 🚀"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
      # - name: "Added Job summary with release version"
      #   run: |
      #     echo "### Release version: ${{ steps.version.outputs.release_version }}" >> $GITHUB_STEP_SUMMARY
      #     echo "### Product: ${{ github.event.inputs.app }}" >> $GITHUB_STEP_SUMMARY

      # # - name: Show Release Status
      # #   uses: ./
      # - name: send notice message
      #   run: |
      #     echo "::notice file=main.js,line=1,col=5,endColumn=7::Missing semicolon"