name: Conditional Job Example

on:
  workflow_dispatch


jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      ADB_HOST: ${{ steps.set_host.outputs.ADB_HOST }}
      ADB_TOKEN: ${{ steps.set_host.outputs.ADB_TOKEN }}
    steps:
    - name: Set needDeploy to yes
      id: set_host
      run: |
        set -x
        ADB_HOST=https://ya.ru
        ADB_TOKEN=secrettoken
        echo "ADB_HOST=$ADB_HOST" >> "$GITHUB_OUTPUT"
        echo "ADB_TOKEN=$ADB_TOKEN" >> "$GITHUB_OUTPUT"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - name: Checking
      env:
        ADB_HOST: ${{ needs.set_host.outputs.ADB_HOST }}
      run: |
        echo "Check from job1: host is $ADB_HOST"
        echo "Check from job1: token is $ADB_TOKEN"
