name: Test
on:
  workflow_dispatch:

jobs:
  one:
    runs-on: ubuntu-latest
    outputs:
      HELLO: "${{ steps.set-some-stuff.outputs.HELLO }}"
    steps:
      - name: one-1
        id: set-some-stuff
        run: |
          echo "HELLO=WORLD" >> "$GITHUB_OUTPUT"

  two:
    runs-on: ubuntu-latest
    needs: one
    steps:
      - name: two-1
        run: |
          var=$(echo "${{ needs.one.outputs.HELLO }}")
          echo $var
  three:
    runs-on: ubuntu-latest
    needs: one
    steps:
      - name: two-2
        run: |
          var2=$(echo "${{ needs.one.outputs.HELLO }}")
          echo $var2
