run-name: "CI: Create product release for ${{ github.event.inputs.app }}"
on:
  workflow_dispatch:
    inputs:
      app:
        description: "app to release"
        default: 'products/hvac-runtime'
        required: true
jobs:
  demo_job_summary:
    runs-on: ubuntu-latest
    steps:
      - name: Fake release version creating
      id: version
        run: |
          echo "Generating release version..."
          echo "RELEASE_VERSION=1.0.0" >> $GITHUB_ENV


      - name: "Added Job summary with release version"
        run: |
          echo "### Release version: ${{ steps.version.outputs.release_version }}" >> $GITHUB_STEP_SUMMARY
          echo "### Product: ${{ github.event.inputs.app }}" >> $GITHUB_STEP_SUMMARY